title: Sam Christian
description: personal website for Sam Christian
url: "https://sam-2727.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author
author:
  name: Sam Christian

lang: en

google_site_verification: uYnbXZEG9JLdzn7Q_KEBNzqAshEbKweYOmU7vNvxr60